<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b9ad674f-85f3-4556-8eb4-df770ef73d07</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Azure.AI.OpenAI" Version="2.8.0-beta.1" />
    <PackageReference Include="Azure.Identity" Version="1.18.0-beta.2" />
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="Microsoft.Agents.AI" Version="1.0.0-preview.260128.1" />
    <PackageReference Include="Microsoft.Agents.AI.Workflows" Version="1.0.0-preview.260128.1" />
    <PackageReference Include="Microsoft.Agents.AI.Hosting" Version="1.0.0-preview.260128.1" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.2.0" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.2.0-preview.1.26063.2" />
    <PackageReference Include="ModelContextProtocol" Version="0.7.0-preview.1" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.12.33" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AgentGroupChat.ServiceDefaults\AgentGroupChat.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>